// Note: This file requires amplify_outputs.json to be generated by running: npx amplify sandbox
// The imports below will work once the Amplify backend is deployed

export interface UploadAssetParams {
  file: File;
  repositoryId: string;
  branch?: string;
  metadata?: Record<string, any>;
  tags?: string[];
}

export interface CreateRepositoryParams {
  name: string;
  description?: string;
  defaultBranch?: string;
}

export interface AssetMetadata {
  fileName: string;
  fileSize: number;
  fileType: string;
  mimeType: string;
  repositoryId: string;
  branch: string;
  lfsOid?: string;
  isLFS: boolean;
}

class AssetAPI {
  private isConfigured = false;

  private async getClient() {
    // Dynamic import to avoid build-time issues
    if (!this.isConfigured) {
      try {
        const { generateClient } = await import('aws-amplify/data');
        const { Amplify } = await import('aws-amplify');
        
        // Check if outputs exist
        try {
          const outputs = await import('@/amplify_outputs.json');
          Amplify.configure(outputs.default || outputs);
          this.isConfigured = true;
        } catch (e) {
          console.warn('Amplify not configured. Run: npx amplify sandbox');
        }
        
        return generateClient();
      } catch (error) {
        console.error('Failed to initialize Amplify client:', error);
        throw new Error('Amplify client not available. Please run: npx amplify sandbox');
      }
    }
  }

  /**
   * Create a new repository
   */
  async createRepository(params: CreateRepositoryParams) {
    const { name, description, defaultBranch = 'main' } = params;

    try {
      const client = await this.getClient();
      const result = await (client as any).models.Repository.create({
        name,
        description,
        defaultBranch,
        lfsEnabled: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });

      return result.data;
    } catch (error) {
      console.error('Error creating repository:', error);
      throw error;
    }
  }

  /**
   * List all repositories
   */
  async listRepositories() {
    try {
      const client = await this.getClient();
      const result = await (client as any).models.Repository.list();
      return result.data || [];
    } catch (error) {
      console.error('Error listing repositories:', error);
      return [];
    }
  }

  /**
   * Get repository by ID
   */
  async getRepository(id: string) {
    try {
      const client = await this.getClient();
      const result = await (client as any).models.Repository.get({ id });
      return result.data;
    } catch (error) {
      console.error('Error getting repository:', error);
      return null;
    }
  }

  /**
   * Upload an asset to a repository
   */
  async uploadAsset(params: UploadAssetParams) {
    const { file, repositoryId, branch = 'main', metadata = {}, tags = [] } = params;

    try {
      const { uploadData } = await import('aws-amplify/storage');
      
      // Determine if file should use LFS (> 1MB)
      const isLFS = file.size > 1024 * 1024;
      const storageKey = isLFS
        ? `lfs-objects/${repositoryId}/${file.name}`
        : `assets/${repositoryId}/${branch}/${file.name}`;

      // Upload file to S3
      const uploadResult = await uploadData({
        key: storageKey,
        data: file,
        options: {
          contentType: file.type,
          metadata: {
            repositoryId,
            branch,
            isLFS: isLFS.toString(),
          },
        },
      }).result;

      // Create asset record in database
      const client = await this.getClient();
      const assetData: any = {
        repositoryId,
        fileName: file.name,
        filePath: storageKey,
        fileSize: file.size,
        fileType: file.name.split('.').pop() || '',
        mimeType: file.type,
        branch,
        isLFS,
        metadata: JSON.stringify(metadata),
        tags,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      if (isLFS) {
        // Generate LFS pointer for large files
        const oid = await this.calculateOID(file);
        assetData.lfsOid = oid;
        assetData.lfsPointer = JSON.stringify({
          version: 'https://git-lfs.github.com/spec/v1',
          oid: `sha256:${oid}`,
          size: file.size,
        });
      }

      const result = await (client as any).models.Asset.create(assetData);

      // Create initial version
      if (result.data?.id) {
        await this.createAssetVersion({
          assetId: result.data.id,
          fileSize: file.size,
          storageKey,
          changeDescription: 'Initial upload',
          lfsOid: isLFS ? assetData.lfsOid : undefined,
        });
      }

      return result.data;
    } catch (error) {
      console.error('Error uploading asset:', error);
      throw error;
    }
  }

  /**
   * Create a new asset version
   */
  async createAssetVersion(params: {
    assetId: string;
    fileSize: number;
    storageKey: string;
    changeDescription?: string;
    lfsOid?: string;
  }) {
    try {
      const client = await this.getClient();
      
      // Get current version count
      const versions = await (client as any).models.AssetVersion.list({
        filter: { assetId: { eq: params.assetId } },
      });

      const versionNumber = (versions.data?.length || 0) + 1;

      const result = await (client as any).models.AssetVersion.create({
        assetId: params.assetId,
        versionNumber,
        commitSha: this.generateCommitSha(),
        fileSize: params.fileSize,
        storageKey: params.storageKey,
        lfsOid: params.lfsOid,
        changeDescription: params.changeDescription,
        createdAt: new Date().toISOString(),
      });

      return result.data;
    } catch (error) {
      console.error('Error creating asset version:', error);
      throw error;
    }
  }

  /**
   * List assets in a repository
   */
  async listAssets(repositoryId: string, branch?: string) {
    try {
      const client = await this.getClient();
      const filter: any = { repositoryId: { eq: repositoryId } };
      if (branch) {
        filter.branch = { eq: branch };
      }

      const result = await (client as any).models.Asset.list({ filter });
      return result.data || [];
    } catch (error) {
      console.error('Error listing assets:', error);
      return [];
    }
  }

  /**
   * Get asset by ID
   */
  async getAsset(id: string) {
    try {
      const client = await this.getClient();
      const result = await (client as any).models.Asset.get({ id });
      return result.data;
    } catch (error) {
      console.error('Error getting asset:', error);
      return null;
    }
  }

  /**
   * Get asset versions
   */
  async getAssetVersions(assetId: string) {
    try {
      const client = await this.getClient();
      const result = await (client as any).models.AssetVersion.list({
        filter: { assetId: { eq: assetId } },
      });
      return result.data || [];
    } catch (error) {
      console.error('Error getting asset versions:', error);
      return [];
    }
  }

  /**
   * Download an asset
   */
  async downloadAsset(storageKey: string) {
    try {
      const { getUrl } = await import('aws-amplify/storage');
      const result = await getUrl({
        key: storageKey,
        options: {
          expiresIn: 3600, // 1 hour
        },
      });

      return result.url;
    } catch (error) {
      console.error('Error downloading asset:', error);
      throw error;
    }
  }

  /**
   * Delete an asset
   */
  async deleteAsset(id: string) {
    try {
      const client = await this.getClient();
      const result = await (client as any).models.Asset.delete({ id });
      return result.data;
    } catch (error) {
      console.error('Error deleting asset:', error);
      throw error;
    }
  }

  /**
   * Calculate OID (SHA256) for LFS
   */
  private async calculateOID(file: File): Promise<string> {
    const buffer = await file.arrayBuffer();
    const hashBuffer = await crypto.subtle.digest('SHA-256', buffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    return hashHex;
  }

  /**
   * Generate a commit SHA
   */
  private generateCommitSha(): string {
    const timestamp = Date.now().toString();
    const random = Math.random().toString(36).substring(2, 15);
    return `${timestamp}-${random}`;
  }
}

export const assetAPI = new AssetAPI();
